### ISSUE TITLE
setproctitle can cause problem loading ray

### ISSUE THREAD

**Issue by chhotii-alex** [ArnaoutLab/diversity#69]
`ray` depends on `setproctitle` and this is causing an error on certain systems. Explicitly importing `setproctitle` may fix this. This is a known ray thing; Google search for what's said about this problem as a first step.

**Comment by IosiaLectus** [comment]
As requested:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jcouch/Code/environments/moore_env/lib/python3.8/site-packages/greylock/__init__.py", line 9, in <module>
    from greylock.metacommunity import Metacommunity
  File "/Users/jcouch/Code/environments/moore_env/lib/python3.8/site-packages/greylock/metacommunity.py", line 17, in <module>
    from greylock.similarity import make_similarity
  File "/Users/jcouch/Code/environments/moore_env/lib/python3.8/site-packages/greylock/similarity.py", line 32, in <module>
    from ray import remote, get, put
  File "/Users/jcouch/Code/environments/moore_env/lib/python3.8/site-packages/ray/__init__.py", line 84, in <module>
    import ray._raylet  # noqa: E402
  File "python/ray/_raylet.pyx", line 169, in init ray._raylet
  File "/Users/jcouch/Code/environments/moore_env/lib/python3.8/site-packages/ray/exceptions.py", line 17, in <module>
    from ray.util.annotations import DeveloperAPI, PublicAPI
  File "/Users/jcouch/Code/environments/moore_env/lib/python3.8/site-packages/ray/util/__init__.py", line 8, in <module>
    from ray.util import rpdb as pdb
  File "/Users/jcouch/Code/environments/moore_env/lib/python3.8/site-packages/ray/util/rpdb.py", line 20, in <module>
    import setproctitle
ImportError: dlopen(/Users/jcouch/Code/environments/moore_env/lib/python3.8/site-packages/ray/thirdparty_files/setproctitle.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_Py_GetArgcArgv'

**Comment by chhotii-alex** [comment]
Josiah was using a really old version of pip; could that explain why he has been the only one to run into this?

Anyway, not reproducible, and making ray optional makes this much less our problem.
